sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5.0"
  - "3.5.2"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip list
script:
  - mamba
  - pip list
